### ISSUE TITLE
License

### ISSUE THREAD

**Issue by perigoso** [DewitteRuben/SketchLeagueRemaster#1]
I wanted to ask your permission to release a a fork of this project under the MIT license.

I want to work on top of the work you have done, to provide an alternative to the now unfortunately dead sketchleague project.

**Comment by DewitteRuben** [comment]
@gimbas 
Oh wow, I had no clue that the official Sketch League died.

As long as my name/github is credited, that would be no problem.

The codebase of this project is rather old, so I'm not sure how good of a foundation this project is. I wrote this as a hobby project when I was still studying CS.

Anyhow, feel free to use the source, I didn't catch this issue until today.. Apologies for that
